In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.2f' % x)
import scipy.stats as stats
import matplotlib.pyplot as plt

Q1. Tom is working in a credit card processing company as a team leader. His team is responsible to validate certain data for new credit card applications. The time spent by his team on an application is normally distributed with average 300 minutes and standard deviation 40 minutes.Tom and his team worked on process improvement to reduce the time spent in processing new applications. After implementing the improvements, Tom checked the time spent by his team on randomly selected 25 new card applications. The average time spent is 290 min. Tom is happy that, though it is a small improvement, it is a step in right direction. He shares the good news with his manager Lisa. But Lisa in not convinced about the improvement. At 95% confidence, is the processes really improved?

In [47]:
stats.norm.ppf(df,0,1)

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]])

In [13]:
df = pd.read_excel("Trough.xlsx")

In [25]:
df


Width
0    8.31
1    8.34
2    8.32
3    8.38
4    8.35
5    8.41
6    8.35
7    8.37
8    8.48
9    8.42
10   8.48
11   8.38
12   8.48
13   8.40
14   8.41
15   8.42
16   8.38
17   8.46
18   8.50
19   8.45
20   8.44
21   8.41
22   8.49
23   8.41
24   8.48
25   8.41
26   8.48
27   8.43
28   8.46
29   8.46
30   8.46
31   8.44
32   8.43
33   8.46
34   8.41
35   8.42
36   8.41
37   8.40
38   8.32
39   8.42
40   8.40
41   8.45
42   8.40
43   8.44
44   8.41
45   8.43
46   8.42
47   8.50
48   8.41

# Question 2

Q2.The Titan Insurance Company has just installed a new incentive payment scheme for its life policy sales-force. It wants to have an early view of the success or failure of the new scheme. Indications are that the sales force is selling more policies but sales always vary in an unpredictable pattern from month to month and it is not clear that the scheme has made a significant difference. Life Insurance companies typically measure the monthly output of a salesperson as the total sum assured for the policies sold by that person during the month.

Titan's new scheme is that the sales force receive low regular salaries but are paid large bonuses related to their output (i.e. to the total sum assured of policies sold by them). The scheme is expensive for the company but they are looking for sales increases to compensate for it. The scheme has now been in operation for four months. It has settled down after fluctuations in the first two months due to the changeover.

To test the effectiveness of the scheme, Titan has taken a random sample of 30 salespeople measured their output in the penultimate month prior to changeover and then measured it in the fourth month after the changeover (they have deliberately chosen months not too close to the changeover).

# Importing CSV 

In [60]:
df.mean()
#8.42
df.std()
#0.05
a,p=stats.ttest_1samp(df,8.46)
p

array([3.14485846e-07])

# Checking the top 5 rows

In [40]:
((8.42-8.46)*7)/0.05

-5.600000000000129

# Checking Summary of data

In [22]:
((201-197.5)*(201-197.5))/197.5

0.0620253164556962

# Check for missing values

In [24]:
((194-197.5)*(194-197.5))/197.5*2

0.1240506329113924

# Plot Histograms and boxplot

In [53]:
p/2

array([0.44607453])

# Describe the five per cent significance test you would apply to these data to determine whether new scheme has significantly raised outputs?

- The level of significance (Alpha ) = 0.05.

- But since the population standard deviation (Sigma) is unknown, we have to use a Tstat test.

- Degree of Freedom: Since the sample is the same for both Sampling tests, we have N-1 degrees of freedom : 29

- Since the sole purpose of the test is to check whether the New scheme is successful compared to old scheme, we would prefer a One-sided T-test.

# What conclusion does the test lead to?

# What reservations have you about this result?

# Suppose it has been calculated that in order for Titan to break even, the average output must increase by £5000. If this figure is alternative hypothesis, what is:

- The probability of a type 1 error?
- The probability of a type 2 error?
- The power of the test?

## Finding Sample Standard Deviation for paired t-test

# Probability of Type II Error ($\beta$)

# Power of the Test:
    
Power of the hypothesis test is 1 minus the probability of Type II error.
Basically the power of a test is the probability that we make the right decision when the null is not correct (i.e. we correctly reject it)

# Extra Question

# What sample size would make the probabilities of type 1 and type 2 errors equal?

In [63]:
df1=df = pd.read_excel("Quiz_Dataset.xlsx")


In [68]:
df1.head()


US_Cars  Japanese_Cars
0       18          24.00
1       15          27.00
2       18          27.00
3       16          25.00
4       17          31.00

In [67]:

df1["US_Cars"]


0      18
1      15
2      18
3      16
4      17
       ..
245    27
246    32
247    28
248    31
249    31
Name: US_Cars, Length: 250, dtype: int64

In [70]:
df1["Japanese_Cars"]

0     24.00
1     27.00
2     27.00
3     25.00
4     31.00
       ... 
245     nan
246     nan
247     nan
248     nan
249     nan
Name: Japanese_Cars, Length: 250, dtype: float64

In [74]:
stats.ttest_ind(df1["US_Cars"],df1["Japanese_Cars"],nan_policy = 'omit')

Ttest_indResult(statistic=-12.536927570602787, pvalue=1.039146026132831e-29)

# Appendix

## Procedure for carrying out a paired t-test
    Suppose a sample of n students were given a diagnostic test before studying a particular
    module and then again after completing the module. We want to find out if, in general,
    our teaching leads to improvements in students’ knowledge/skills (i.e. test scores). We
    can use the results from our sample of students to draw conclusions about the impact of
    this module in general
    
   Let x = test score before the module, y = test score after the module
   To test the null hypothesis that the true mean difference is zero, the procedure is as
   follows:
    1. Calculate the difference (di = yi − xi) between the two observations on each pair,
    making sure you distinguish between positive and negative differences.
    2. Calculate the mean difference, d.
    3. Calculate the standard deviation of the differences, sd, and use this to calculate the
    standard error of the mean difference, SE(d) = sd/√n
    4. Calculate the t-statistic, which is given by T =d/SE(d), Under the null hypothesis, this statistic follows a t-distribution with n − 1 degrees of freedom.
    5. Use tables of the t-distribution to compare your value for T to the tn-1 distribution.
    This will give the p-value for the paired t-test.